### ISSUE TITLE
Generate SLSA 3 Provenance 

### ISSUE THREAD

**Issue by joycebrum** [sigstore/helm-sigstore#102]
**Description**

Hi, I am Joyce, working on behalf of Google and the [Open Source Security Foundation (OpenSSF)](https://openssf.org/) to help open source projects to improve their supply chain security.

I would like to offer help to config helm-sigstore's builds to generate a [SLSA Level 3 Provenance](https://slsa.dev/provenance/v0.2). The [Supply chain Levels for Software Artifacts, or SLSA (salsa)](https://slsa.dev/) aims to improve security in the build process, to do that it has defined [4 levels](https://slsa.dev/spec/v0.1/levels) of build integrity. 

I would suggest, since it seems you already user goreleaser to build and release on github, to use the [SLSA Go Builder](https://github.com/slsa-framework/slsa-github-generator/blob/main/internal/builders/go/README.md) which do the same as the goreleaser but also generates and sign the artifacts, besides being a Level 3 build process. 

Are you open to a PR with these changes? 

It could also contain changes on the README with:

- A SLSA Level 3 badge
- A brief paragraph to end-user know how to verify the artifact integrity using the provenance.

**Comment by sabre1041** [comment]
@joycebrum Happy to take on the contribution!
